package io.jboot.fly.model;

import io.jboot.db.annotation.Table;
import io.jboot.fly.model.base.BaseCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "category", primaryKey = "id")
public class Category extends BaseCategory<Category> {
	
}
