package io.jboot.fly.model;

import io.jboot.db.annotation.Table;
import io.jboot.fly.model.base.BasePost;
import io.jboot.fly.utils.JsoupUtils;

/**
 * Generated by Jboot.
 */
@Table(tableName = "post", primaryKey = "id")
public class Post extends BasePost<Post> {

    public static final String EDIT_MODE_HTML = "html";
    public static final String EDIT_MODE_MARKDOWN = "markdown";

    /**
     * 状态：正常发布，未结帖
     * 一般情况下，在 "状态" 的数据库设计中，正常的状态 大于等于0，非正常状态小于0
     * 这样的好处是，判断这个 对象 是否 "正常"时，只需要判断是否大于0就行了，而不需要判断 等于多少(和多少)
     */
    public static final int STATUS_NORMAL = 0;

    /**
     * 状态：正常发布，已经结帖
     */
    public static final int STATUS_FINISHED = 9;

    /**
     * 状态：审核中，不能显示在列表上，详情页不能显示，404错误
     */
    public static final int STATUS_AUDITING = -1;

    /**
     * 状态：已经被删除了，列表不能显示，详情访问404
     */
    public static final int STATUS_DELETE = -2;


    public boolean canShow() {
        Integer status = getStatus();
        return status != null && status >= 0;
    }


    public boolean isFinished() {
        Integer status = getStatus();
        return status != null && status == STATUS_FINISHED;
    }

    public boolean isRecommend() {
        Boolean r = getRecommend();
        return r != null && r == true;
    }

    public String contentText() {
        String content = getContent();
        return content == null ? content : JsoupUtils.getText(content);
    }


}
