package io.jboot.fly.model;

import io.jboot.db.annotation.Table;
import io.jboot.fly.model.base.BaseUserCollection;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_collection", primaryKey = "id")
public class UserCollection extends BaseUserCollection<UserCollection> {
	
}
