package io.jboot.fly.model;

import io.jboot.db.annotation.Table;
import io.jboot.fly.model.base.BaseUserMessage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_message", primaryKey = "id")
public class UserMessage extends BaseUserMessage<UserMessage> {

    public static final int TYPE_COMMENT = 1;

}
