package io.jboot.fly.model;

import io.jboot.db.annotation.Table;
import io.jboot.fly.model.base.BaseUser;
import io.jboot.utils.StringUtils;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {

    public static final int STATUS_NORMAL = 0;
    public static final int STATUS_AUDITING = -1;
    public static final int STATUS_FROZEN = -9;

    @Override
    public String getAvatar() {
        String avatar = super.getAvatar();
        if (StringUtils.isBlank(avatar)) {
            avatar = "/static/images/avatar/default.png";
        }
        return avatar;
    }

    public boolean isAdmin() {
        return "admin".equals(getRole());
    }


    /**
     * 是否正常
     *
     * @return
     */
    public boolean isNormal() {
        Integer status = getStatus();
        return status != null && STATUS_NORMAL >= 0;
    }

    /**
     * 是否已经冻结
     *
     * @return
     */
    public boolean isFrozen() {
        Integer status = getStatus();
        return status != null && STATUS_FROZEN == status;
    }

    /**
     * 是否在审核中
     *
     * @return
     */
    public boolean isAuditing() {
        Integer status = getStatus();
        return status != null && STATUS_AUDITING == status;
    }
}
