package io.jboot.fly.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCollection<M extends BaseUserCollection<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "UserCollection:add";
    public static final String ACTION_DELETE = "UserCollection:delete";
    public static final String ACTION_UPDATE = "UserCollection:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setPostId(java.lang.String postId) {
		set("post_id", postId);
	}
	
	public java.lang.String getPostId() {
		return getStr("post_id");
	}

	public void setPostTitle(java.lang.String postTitle) {
		set("post_title", postTitle);
	}
	
	public java.lang.String getPostTitle() {
		return getStr("post_title");
	}

	public void setPostContent(java.lang.String postContent) {
		set("post_content", postContent);
	}
	
	public java.lang.String getPostContent() {
		return getStr("post_content");
	}

	public void setPostUserId(java.lang.String postUserId) {
		set("post_user_id", postUserId);
	}
	
	public java.lang.String getPostUserId() {
		return getStr("post_user_id");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
