package io.jboot.fly.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMessage<M extends BaseUserMessage<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "UserMessage:add";
    public static final String ACTION_DELETE = "UserMessage:delete";
    public static final String ACTION_UPDATE = "UserMessage:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setFromUserId(java.lang.String fromUserId) {
		set("from_user_id", fromUserId);
	}
	
	public java.lang.String getFromUserId() {
		return getStr("from_user_id");
	}

	public void setToUserId(java.lang.String toUserId) {
		set("to_user_id", toUserId);
	}
	
	public java.lang.String getToUserId() {
		return getStr("to_user_id");
	}

	public void setPostId(java.lang.String postId) {
		set("post_id", postId);
	}
	
	public java.lang.String getPostId() {
		return getStr("post_id");
	}

	public void setCommentId(java.lang.String commentId) {
		set("comment_id", commentId);
	}
	
	public java.lang.String getCommentId() {
		return getStr("comment_id");
	}

	public void setAction(java.lang.String action) {
		set("action", action);
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
