package io.jboot.fly.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "User:add";
    public static final String ACTION_DELETE = "User:delete";
    public static final String ACTION_UPDATE = "User:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public void setRole(java.lang.String role) {
		set("role", role);
	}
	
	public java.lang.String getRole() {
		return getStr("role");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setEmailStatus(java.lang.Integer emailStatus) {
		set("email_status", emailStatus);
	}
	
	public java.lang.Integer getEmailStatus() {
		return getInt("email_status");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setMobileStatus(java.lang.Integer mobileStatus) {
		set("mobile_status", mobileStatus);
	}
	
	public java.lang.Integer getMobileStatus() {
		return getInt("mobile_status");
	}

	public void setPoint(java.lang.Long point) {
		set("point", point);
	}
	
	public java.lang.Long getPoint() {
		return getLong("point");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setAuthInfo(java.lang.String authInfo) {
		set("auth_info", authInfo);
	}
	
	public java.lang.String getAuthInfo() {
		return getStr("auth_info");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}

	public void setSignature(java.lang.String signature) {
		set("signature", signature);
	}
	
	public java.lang.String getSignature() {
		return getStr("signature");
	}

	public void setPostCount(java.lang.Long postCount) {
		set("post_count", postCount);
	}
	
	public java.lang.Long getPostCount() {
		return getLong("post_count");
	}

	public void setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
	}
	
	public java.lang.Long getCommentCount() {
		return getLong("comment_count");
	}

	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}
	
	public java.lang.String getWechat() {
		return getStr("wechat");
	}

	public void setWeibo(java.lang.String weibo) {
		set("weibo", weibo);
	}
	
	public java.lang.String getWeibo() {
		return getStr("weibo");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setSite(java.lang.String site) {
		set("site", site);
	}
	
	public java.lang.String getSite() {
		return getStr("site");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setCreateSource(java.lang.String createSource) {
		set("create_source", createSource);
	}
	
	public java.lang.String getCreateSource() {
		return getStr("create_source");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setLogged(java.util.Date logged) {
		set("logged", logged);
	}
	
	public java.util.Date getLogged() {
		return get("logged");
	}

	public void setActivated(java.util.Date activated) {
		set("activated", activated);
	}
	
	public java.util.Date getActivated() {
		return get("activated");
	}

}
